#!/usr/bin/env bash
# This script kills the '7-highlander' process.

process_name="7-highlander"

pid=$(ps aux | grep "$process_name | grep -v grep | awk '{print $print $2}')

if [[ -n $pid ]];
then
	kill $pid
fi
