#!/usr/bin/env bash
# This script displays the content of the file '/etc/passwd'
# displays only: username, user id, home directory path for the user.
# use while loop only.

while IFS=: read -r username userid _ _ homedir _
do
    echo "$username:$userid:$homedir"
done < /etc/passwd