#!/usr/bin/env bash
# This script displays the content of the file '/etc/passwd', using the while loop + IFS..

# Set the Internal Field Separator to :
IFS=":"

# Read the /etc/passwd file line by line
while read -r USERNAME PASSWORD USER_ID GROUP_ID INFO HOME_DIRECTORY COMMAND_SHELL
do
    echo "The user $USERNAME is part of the $GROUP_ID gang, lives in $HOME_DIRECTORY and rides $COMMAND_SHELL. $USER_ID's place is protected by the passcode $PASSWORD, more info about the user here: $INFO"
done < /etc/passwd
