#!/usr/bin/env bash
# This script configures an Ubuntu server

# Backup the original hosts file
sudo cp /etc/hosts /etc/hosts.bak

# Add the custom IP addresses
echo "127.0.0.2 localhost" | sudo tee -a /etc/hosts
echo "8.8.8.8 facebook.com" | sudo tee -a /etc/hosts

